### ISSUE TITLE
Sugestão de ajuste ao atualizar um cliente com id inexistente

### ISSUE THREAD

**Issue by oliveiralex** [gabrieltav/desafio-crud-client-bootcamp-devsuperior#1]
Olá Gabriel, meu nome é Alexandre e estou corrigindo sua atividade.

Seu trabalho foi aceito, parabéns! Para ficar 100%, sugiro que você faça o ajuste ao atualizar um cliente com id inexistente. Ao tentar atualizar este cliente, está retornando um 200 ok. O correto seria retornar 404 not found e aquela mensagem com corpo indicando para o usuário.

Abraço e bons estudos

**Comment by gabrieltav** [comment]
ok! Erro corrigido, muito obrigado...

**Comment by gabrieltav** [comment]
> Olá Gabriel, meu nome é Alexandre e estou corrigindo sua atividade.
> 
> Seu trabalho foi aceito, parabéns! Para ficar 100%, sugiro que você faça o ajuste ao atualizar um cliente com id inexistente. Ao tentar atualizar este cliente, está retornando um 200 ok. O correto seria retornar 404 não encontrado e aquela mensagem com corpo indicando para o usuário.
> 
> Abraço e bons estudos

OK! Erro corrigido, muito obrigado ...
